// Auto-generated by generate_seq.cjs
import { Chapter } from "./data";

export const sequencesChapter: Chapter = {
  "id": "sequences",
  "title": "Sequences and Series",
  "tagline": "Mastering AP, GP, and Special Series",
  "color": "algebra",
  "totalConcepts": 5,
  "concepts": [
    {
      "id": "seq-c1",
      "chapterId": "sequences",
      "title": "Concept 1",
      "subtitle": "Sequences and Series Basics - Definitions of Sequence, Progression, and Series",
      "difficulty": "Medium",
      "order": 1,
      "formulas": [
        {
          "id": "seq-c1-f1",
          "name": "Sequences and Series Basics - ...",
          "descriptionAbove": "A sequence is an arrangement of numbers in a definite order according to a rule. A progression is a sequence whose terms follow a certain distinct mathematical pattern.",
          "expression": {
            "lhs": "\\text{Series: } S_n = a_1 + a_2 + a_3 + \\dots + a_n",
            "num": "",
            "den": "",
            "color": "info"
          },
          "descriptionBelow": "It can be a finite series (countable terms) or an infinite series (endless terms). Understanding these terms is the foundation for AP and GP.",
          "explanation": "While SSC CGL rarely asks for direct definitions, understanding the terminology is crucial for interpreting word problems. Knowing whether a question asks for a \"term in a progression\" or the \"sum of a series\" determines your entire approach.",
          "mnemonic": "",
          "questions": [
            {
              "id": "q1",
              "text": "Which of the following mathematical constructs specifically represents a \"Finite Series\" according to standard algebraic definitions?",
              "options": [
                "$2, 4, 6, 8, 10, \\dots$",
                "$1 + 3 + 5 + 7 + \\dots$",
                "$5 + 10 + 15 + 20 + 25$",
                "$1, 4, 9, 16, 25$"
              ],
              "correctIndex": 2,
              "solution": "A series must be the sum of sequence terms.\nA finite series must have a terminating end.\nOption C represents a finite sum of exact terms."
            },
            {
              "id": "q2",
              "text": "If a sequence is defined by the rule $a_n = n^2 + 1$, what is the sum of the finite series formed by its first 3 terms?",
              "options": [
                "$14$",
                "$17$",
                "$20$",
                "$23$"
              ],
              "correctIndex": 1,
              "solution": "Identify the rule: $a_n = n^2 + 1$.\nCalculate the first 3 terms of the progression:\n$a_1 = 1^2 + 1 = 2$\n$a_2 = 2^2 + 1 = 5$\n$a_3 = 3^2 + 1 = 10$\nForm the series: $2 + 5 + 10 = 17$."
            },
            {
              "id": "q3",
              "text": "A sequence has terms that follow a certain pattern but goes on indefinitely. If we express the sum of all these terms, what is the correct terminology for this mathematical entity?",
              "options": [
                "Infinite Progression",
                "Infinite Series",
                "Finite Sequence",
                "Indefinite Sequence"
              ],
              "correctIndex": 1,
              "solution": "The question states we are expressing the \"sum of all these terms\". Summation implies it is a \"Series\".\nThe sequence \"goes on indefinitely\", meaning it does not end.\nCombining both facts, the entity is an Infinite Series."
            },
            {
              "id": "q4",
              "text": "What is the difference between a sequence and a series?",
              "options": [
                "A sequence is numbers added, a series is numbers listed.",
                "A sequence is numbers listed, a series is numbers added.",
                "They are exactly the same thing.",
                "A sequence is infinite, a series is finite."
              ],
              "correctIndex": 1,
              "solution": "A sequence is an ordered list of numbers.\nA series is the sum of a list of numbers.\nTherefore, option B is correct."
            }
          ]
        }
      ]
    },
    {
      "id": "seq-c2",
      "chapterId": "sequences",
      "title": "Concept 2",
      "subtitle": "Arithmetic Progression (AP) - Nth Term - General Term Formulas of an AP",
      "difficulty": "Medium",
      "order": 2,
      "formulas": [
        {
          "id": "seq-c2-f1",
          "name": "Arithmetic Progression (AP) - ...",
          "descriptionAbove": "The Nth term from the beginning of an Arithmetic Progression is the first term plus the number of steps multiplied by the common difference.",
          "expression": {
            "lhs": "a_n = a + (n-1)d",
            "num": "",
            "den": "",
            "color": "info"
          },
          "descriptionBelow": "Where $a$ = first term, $d$ = common difference. Also, the Nth term from the end is $l - (n-1)d$ where $l$ is the last term.",
          "explanation": "These are the foundational blocks of AP. Use the end-term formula directly instead of reversing the whole series.",
          "mnemonic": "",
          "questions": [
            {
              "id": "q1",
              "text": "In an Arithmetic Progression, the first term is $7$ and the common difference is $-3$. What is the 15th term?",
              "options": [
                "$35$",
                "$-35$",
                "$-38$",
                "$-42$"
              ],
              "correctIndex": 1,
              "solution": "Identify given values: $a = 7$, $d = -3$, $n = 15$.\nFormula: $a_n = a + (n-1)d$.\nSubstitute: $a_{15} = 7 + (15-1)(-3) = 7 - 42 = -35$."
            },
            {
              "id": "q2",
              "text": "Which term of the AP $5, 9, 13, 17, \\dots$ is $81$?",
              "options": [
                "$19^{th}$",
                "$20^{th}$",
                "$21^{st}$",
                "$22^{nd}$"
              ],
              "correctIndex": 1,
              "solution": "Given: $a = 5$, $d = 9 - 5 = 4$, $a_n = 81$.\nSubstitute: $81 = 5 + (n-1)4$.\nSolve: $76 = 4(n-1) \\implies n-1 = 19 \\implies n = 20$."
            },
            {
              "id": "q3",
              "text": "Find the 10th term from the end of the AP: $10, 15, 20, \\dots, 135$.",
              "options": [
                "$85$",
                "$90$",
                "$95$",
                "$100$"
              ],
              "correctIndex": 1,
              "solution": "Given: AP is $10, 15, \\dots, 135$. Common diff $d = 5$. Last term $l = 135$.\nFormula: Term from end $= l - (n-1)d$.\nSubstitute: $135 - (10-1)5 = 135 - 45 = 90$."
            },
            {
              "id": "q4",
              "text": "The 4th term from the end of an AP is $22$. If the common difference is $-2$, what is the last term of the AP?",
              "options": [
                "$16$",
                "$14$",
                "$28$",
                "$30$"
              ],
              "correctIndex": 0,
              "solution": "Given: Term from end $= 22$, $n = 4$, $d = -2$.\nFormula: Term from end $= l - (n-1)d$.\nSubstitute: $22 = l - (4-1)(-2) \\implies 22 = l + 6 \\implies l = 16$."
            }
          ]
        }
      ]
    },
    {
      "id": "seq-c3",
      "chapterId": "sequences",
      "title": "Concept 3",
      "subtitle": "Sum of First n Terms of an AP - Summation Formulas and Deductions",
      "difficulty": "Medium",
      "order": 3,
      "formulas": [
        {
          "id": "seq-c3-f1",
          "name": "Sum of First n Terms of an AP ...",
          "descriptionAbove": "To find the sum of an Arithmetic Progression, you can average the first and last terms, then multiply by the total number of terms.",
          "expression": {
            "lhs": "S_n = \\frac{n}{2}[2a + (n-1)d] \\text{ OR } S_n = \\frac{n}{2}[a + l]",
            "num": "",
            "den": "",
            "color": "info"
          },
          "descriptionBelow": "Number of terms $n = \\frac{l - a}{d} + 1$. Also, $a_n = S_n - S_{n-1}$.",
          "explanation": "Use these when asked to find the total sum of a series. The second formula is faster if you already know the last term $l$.",
          "mnemonic": "",
          "questions": [
            {
              "id": "q1",
              "text": "Find the sum of all natural numbers between 100 and 200 which are divisible by 3.",
              "options": [
                "$4950$",
                "$5000$",
                "$4851$",
                "$4900$"
              ],
              "correctIndex": 0,
              "solution": "First number $>100$ divisible by 3 is $102$. Last is $198$.\n$n = \\frac{198-102}{3} + 1 = 33$.\nSum $S_{33} = \\frac{33}{2}[102 + 198] = \\frac{33}{2}[300] = 4950$."
            },
            {
              "id": "q2",
              "text": "How many terms of the AP $24, 21, 18, \\dots$ must be taken so that their sum is 78?",
              "options": [
                "$4$ or $13$",
                "$5$ or $12$",
                "$4$ only",
                "$13$ only"
              ],
              "correctIndex": 0,
              "solution": "Given $a=24, d=-3, S_n=78$.\n$78 = \\frac{n}{2}[48 + (n-1)(-3)] \\implies 156 = 51n - 3n^2$.\n$n^2 - 17n + 52 = 0 \\implies (n-4)(n-13) = 0$."
            },
            {
              "id": "q3",
              "text": "The sum of the first $n$ terms of an AP is given by $S_n = 4n^2 - n$. What is the common difference of this AP?",
              "options": [
                "$3$",
                "$4$",
                "$8$",
                "$7$"
              ],
              "correctIndex": 2,
              "solution": "Rule: If $S_n = An^2 + Bn$, the common difference $d = 2A$.\nHere, $A = 4$.\nTherefore, $d = 2(4) = 8$."
            },
            {
              "id": "q4",
              "text": "The sum of first $n$ terms of a series is given by $S_n = 2n^2 + 3n$. Find the 10th term.",
              "options": [
                "$41$",
                "$43$",
                "$38$",
                "$45$"
              ],
              "correctIndex": 0,
              "solution": "Formula: $a_n = S_n - S_{n-1}$.\n$S_{10} = 2(100) + 30 = 230$.\n$S_9 = 2(81) + 27 = 189$.\n$a_{10} = 230 - 189 = 41$."
            }
          ]
        }
      ]
    },
    {
      "id": "seq-c4",
      "chapterId": "sequences",
      "title": "Concept 4",
      "subtitle": "Geometric Progression (GP) - General Term of a GP",
      "difficulty": "Medium",
      "order": 4,
      "formulas": [
        {
          "id": "seq-c4-f1",
          "name": "Geometric Progression (GP) - G...",
          "descriptionAbove": "A sequence is a GP if the ratio of any term to its preceding term is constant (Common Ratio $r = \\frac{a_{n+1}}{a_n}$).",
          "expression": {
            "lhs": "a_n = ar^{n-1}",
            "num": "",
            "den": "",
            "color": "info"
          },
          "descriptionBelow": "General format of GP sequence: $a, ar, ar^2, ar^3, \\dots, ar^{n-1}, \\dots$.",
          "explanation": "AP relies on addition; GP relies on multiplication. Use these formulas for population growth, compound interest structure problems, or any sequence scaling by a factor.",
          "mnemonic": "",
          "questions": [
            {
              "id": "q1",
              "text": "Which of the following sequences represents a valid Geometric Progression?",
              "options": [
                "$2, 4, 6, 8, \\dots$",
                "$3, 9, 18, 36, \\dots$",
                "$4, -8, 16, -32, \\dots$",
                "$1, 4, 9, 16, \\dots$"
              ],
              "correctIndex": 2,
              "solution": "A GP must have a constant ratio $r = \\frac{a_2}{a_1} = \\frac{a_3}{a_2}$.\nOption C: $-8/4 = -2$, and $16/-8 = -2$. Ratio is constant."
            },
            {
              "id": "q2",
              "text": "In a GP, the first term is $3$ and the common ratio is $2$. What is the 6th term?",
              "options": [
                "$192$",
                "$96$",
                "$48$",
                "$384$"
              ],
              "correctIndex": 1,
              "solution": "Given $a = 3$, $r = 2$, $n = 6$.\nFormula: $a_n = ar^{n-1}$.\nSubstitute: $a_6 = 3(2^{6-1}) = 3(32) = 96$."
            },
            {
              "id": "q3",
              "text": "The 3rd term of a GP is $12$ and the 6th term is $96$. What is the first term $a$?",
              "options": [
                "$2$",
                "$3$",
                "$4$",
                "$6$"
              ],
              "correctIndex": 1,
              "solution": "$ar^2 = 12$ and $ar^5 = 96$.\nDivide them: $r^3 = 8 \\implies r = 2$.\nSubstitute: $a(2^2) = 12 \\implies 4a = 12 \\implies a = 3$."
            },
            {
              "id": "q4",
              "text": "What is the common ratio of the GP $5, 15, 45, 135, \\dots$?",
              "options": [
                "$2$",
                "$3$",
                "$4$",
                "$5$"
              ],
              "correctIndex": 1,
              "solution": "The common ratio $r = a_2 / a_1$.\n$r = 15 / 5 = 3$."
            }
          ]
        }
      ]
    },
    {
      "id": "seq-c5",
      "chapterId": "sequences",
      "title": "Concept 5",
      "subtitle": "Special Series Tricks - Telescoping Fractions",
      "difficulty": "Medium",
      "order": 5,
      "formulas": [
        {
          "id": "seq-c5-f1",
          "name": "Special Series Tricks - Telesc...",
          "descriptionAbove": "When fractions have consecutive products in the denominator (like $5 \\times 6, 6 \\times 7$), they can telescope and cancel out the middle terms.",
          "expression": {
            "lhs": "\\text{Sum} = \\frac{1}{d} \\left[ \\frac{1}{\\text{First}} - \\frac{1}{\\text{Last}} \\right]",
            "num": "",
            "den": "",
            "color": "info"
          },
          "descriptionBelow": "Where $d$ is the common difference $b-a$, \"First\" is the first term of the first denominator, and \"Last\" is the last term of the last denominator.",
          "explanation": "Use this formula to jump straight to the answer without manual LCM calculations for series of the form $\\frac{1}{a \\times b} + \\frac{1}{b \\times c}$.",
          "mnemonic": "",
          "questions": [
            {
              "id": "q1",
              "text": "Find the sum of the series: $\\frac{1}{3 \\times 5} + \\frac{1}{5 \\times 7} + \\dots + \\frac{1}{21 \\times 23}$.",
              "options": [
                "$\\frac{20}{69}$",
                "$\\frac{10}{69}$",
                "$\\frac{2}{23}$",
                "$\\frac{5}{69}$"
              ],
              "correctIndex": 1,
              "solution": "Identify common difference $d = 5-3 = 2$.\nFirst $= 3$, Last $= 23$.\n$\\text{Sum} = \\frac{1}{2} \\left[ \\frac{1}{3} - \\frac{1}{23} \\right] = \\frac{1}{2} \\left[ \\frac{20}{69} \\right] = \\frac{10}{69}$."
            },
            {
              "id": "q2",
              "text": "What is the value of $\\frac{1}{2 \\times 5} + \\frac{1}{5 \\times 8} + \\dots + \\frac{1}{29 \\times 32}$?",
              "options": [
                "$\\frac{5}{32}$",
                "$\\frac{15}{64}$",
                "$\\frac{15}{32}$",
                "$\\frac{5}{64}$"
              ],
              "correctIndex": 0,
              "solution": "Common difference $d = 5-2 = 3$.\nFirst $= 2$, Last $= 32$.\n$\\text{Sum} = \\frac{1}{3} \\left[ \\frac{1}{2} - \\frac{1}{32} \\right] = \\frac{1}{3} \\left[ \\frac{15}{32} \\right] = \\frac{5}{32}$."
            },
            {
              "id": "q3",
              "text": "Sum of: $\\frac{1}{1 \\times 2} + \\frac{1}{2 \\times 3} + \\dots + \\frac{1}{99 \\times 100}$",
              "options": [
                "$\\frac{99}{100}$",
                "$\\frac{1}{100}$",
                "$\\frac{100}{99}$",
                "$1$"
              ],
              "correctIndex": 0,
              "solution": "$d = 2-1 = 1$. First $= 1$, Last $= 100$.\n$\\text{Sum} = \\frac{1}{1} \\left[ \\frac{1}{1} - \\frac{1}{100} \\right] = \\frac{99}{100}$."
            },
            {
              "id": "q4",
              "text": "Evaluate $\\frac{1}{4 \\times 7} + \\frac{1}{7 \\times 10} + \\frac{1}{10 \\times 13}$",
              "options": [
                "$\\frac{3}{52}$",
                "$\\frac{9}{52}$",
                "$\\frac{1}{52}$",
                "$\\frac{3}{13}$"
              ],
              "correctIndex": 0,
              "solution": "$d = 7-4 = 3$. First $= 4$, Last $= 13$.\n$\\text{Sum} = \\frac{1}{3} \\left[ \\frac{1}{4} - \\frac{1}{13} \\right] = \\frac{1}{3} \\left[ \\frac{9}{52} \\right] = \\frac{3}{52}$."
            }
          ]
        }
      ]
    }
  ]
};
