/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResultConceptIdRouteImport } from './routes/result.$conceptId'
import { Route as QuizConceptIdRouteImport } from './routes/quiz.$conceptId'
import { Route as ConceptConceptIdRouteImport } from './routes/concept.$conceptId'
import { Route as ChapterChapterIdRouteImport } from './routes/chapter.$chapterId'
import { Route as AdminChapterChapterIdRouteImport } from './routes/admin.chapter.$chapterId'
import { Route as AdminConceptChapterIdConceptIdRouteImport } from './routes/admin.concept.$chapterId.$conceptId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResultConceptIdRoute = ResultConceptIdRouteImport.update({
  id: '/result/$conceptId',
  path: '/result/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizConceptIdRoute = QuizConceptIdRouteImport.update({
  id: '/quiz/$conceptId',
  path: '/quiz/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptConceptIdRoute = ConceptConceptIdRouteImport.update({
  id: '/concept/$conceptId',
  path: '/concept/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterChapterIdRoute = ChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChapterChapterIdRoute = AdminChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConceptChapterIdConceptIdRoute =
  AdminConceptChapterIdConceptIdRouteImport.update({
    id: '/concept/$chapterId/$conceptId',
    path: '/concept/$chapterId/$conceptId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/quiz/$conceptId': typeof QuizConceptIdRoute
  '/result/$conceptId': typeof ResultConceptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/chapter/$chapterId': typeof AdminChapterChapterIdRoute
  '/admin/concept/$chapterId/$conceptId': typeof AdminConceptChapterIdConceptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/quiz/$conceptId': typeof QuizConceptIdRoute
  '/result/$conceptId': typeof ResultConceptIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/chapter/$chapterId': typeof AdminChapterChapterIdRoute
  '/admin/concept/$chapterId/$conceptId': typeof AdminConceptChapterIdConceptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/quiz/$conceptId': typeof QuizConceptIdRoute
  '/result/$conceptId': typeof ResultConceptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/chapter/$chapterId': typeof AdminChapterChapterIdRoute
  '/admin/concept/$chapterId/$conceptId': typeof AdminConceptChapterIdConceptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/progress'
    | '/settings'
    | '/chapter/$chapterId'
    | '/concept/$conceptId'
    | '/quiz/$conceptId'
    | '/result/$conceptId'
    | '/admin/'
    | '/admin/chapter/$chapterId'
    | '/admin/concept/$chapterId/$conceptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/settings'
    | '/chapter/$chapterId'
    | '/concept/$conceptId'
    | '/quiz/$conceptId'
    | '/result/$conceptId'
    | '/admin'
    | '/admin/chapter/$chapterId'
    | '/admin/concept/$chapterId/$conceptId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/progress'
    | '/settings'
    | '/chapter/$chapterId'
    | '/concept/$conceptId'
    | '/quiz/$conceptId'
    | '/result/$conceptId'
    | '/admin/'
    | '/admin/chapter/$chapterId'
    | '/admin/concept/$chapterId/$conceptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  ChapterChapterIdRoute: typeof ChapterChapterIdRoute
  ConceptConceptIdRoute: typeof ConceptConceptIdRoute
  QuizConceptIdRoute: typeof QuizConceptIdRoute
  ResultConceptIdRoute: typeof ResultConceptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/result/$conceptId': {
      id: '/result/$conceptId'
      path: '/result/$conceptId'
      fullPath: '/result/$conceptId'
      preLoaderRoute: typeof ResultConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$conceptId': {
      id: '/quiz/$conceptId'
      path: '/quiz/$conceptId'
      fullPath: '/quiz/$conceptId'
      preLoaderRoute: typeof QuizConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$conceptId': {
      id: '/concept/$conceptId'
      path: '/concept/$conceptId'
      fullPath: '/concept/$conceptId'
      preLoaderRoute: typeof ConceptConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId': {
      id: '/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof ChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chapter/$chapterId': {
      id: '/admin/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/admin/chapter/$chapterId'
      preLoaderRoute: typeof AdminChapterChapterIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/concept/$chapterId/$conceptId': {
      id: '/admin/concept/$chapterId/$conceptId'
      path: '/concept/$chapterId/$conceptId'
      fullPath: '/admin/concept/$chapterId/$conceptId'
      preLoaderRoute: typeof AdminConceptChapterIdConceptIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChapterChapterIdRoute: typeof AdminChapterChapterIdRoute
  AdminConceptChapterIdConceptIdRoute: typeof AdminConceptChapterIdConceptIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminChapterChapterIdRoute: AdminChapterChapterIdRoute,
  AdminConceptChapterIdConceptIdRoute: AdminConceptChapterIdConceptIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  ChapterChapterIdRoute: ChapterChapterIdRoute,
  ConceptConceptIdRoute: ConceptConceptIdRoute,
  QuizConceptIdRoute: QuizConceptIdRoute,
  ResultConceptIdRoute: ResultConceptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
